### PR TITLE
fleshing out 'line item' objects

### PR DESCRIPTION
**Pull request by ynagasaki**
/cc @mikesss @apostrophest

How should I organize my object stuffs? Should I like... make a new JS "class" or something.

### CODE REVIEW

**Comment by mikesss** [comment]
I don't understand the question

**Comment by ynagasaki** [comment]
Hu, well in the view1.js file, I have an array of "line items" hardcoded for now, and each "line item" is just one of those simple { "key": value } JS objects (a "hash"?). And I'm wondering if that's acceptable or if I should make my own "class" somewhere.

**Comment by apostrophest** [comment]
It looks like you made each line item a string??

I dunno, I liked this talk by the guy that made Clojure. http://www.infoq.com/presentations/Simple-Made-Easy One of his recommendations is to keep data as data as much as possible. So if an endpoint returns JSON that's a list of line item schemas, you would write code that acts on the list of JSON schemas rather than creating a Collection class composed of LineItem classes.

Given the seemingly scope of what you're talking about doing, I would just leave stuff as plain old JavaScript objects.

**Comment by ynagasaki** [comment]
ok thx

**Pull request merged**
